import React from 'react';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export default function AIPolicyPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="prose prose-lg max-w-none">
        <h1>AI Policy & Ethics</h1>
        <p className="text-gray-600 text-lg">Last Updated: September 27, 2025</p>

        <p>
          This policy outlines how RealVibeAI Realty ("we," "us," or "our") uses artificial intelligence (AI) in our services. 
          We are committed to transparency, ethical AI practices, and user empowerment.
        </p>

        <h2>1. AI in Our Services</h2>
        <p>We use AI to provide the following features:</p>

        <h3>Lead Management & Outreach</h3>
        <ul>
          <li><strong>Lead Qualification</strong>: Our AI analyzes lead data to score prospects as Hot, Warm, or Cold, helping agents prioritize their efforts</li>
          <li><strong>Automated Responses</strong>: Initial lead follow-ups and confirmations may be generated by AI</li>
          <li><strong>Follow-Up Sequences</strong>: AI-powered nurturing emails sent at 48 hours, 7 days, and monthly intervals</li>
          <li><strong>Social Profile Enrichment</strong>: AI assists in gathering publicly available professional information</li>
        </ul>

        <h3>Virtual Staging</h3>
        <ul>
          <li><strong>Property Enhancement</strong>: We use generative AI to create realistic virtual staging for property photos</li>
          <li><strong>Room Transformation</strong>: AI generates furniture and decor suggestions for empty spaces</li>
        </ul>

        <h2>2. Transparency & Disclosure</h2>
        <ul>
          <li>All AI-generated communications include clear disclosure: "This message was generated by AI and may contain imperfections"</li>
          <li>AI-powered features are clearly labeled throughout our platform</li>
          <li>Users are informed when interacting with AI systems</li>
          <li>All AI-generated outreach is logged for audit purposes</li>
        </ul>

        <h2>3. User Control & Consent</h2>
        <h3>Opt-In Requirements</h3>
        <ul>
          <li><strong>Automated Follow-Ups</strong>: Users must explicitly opt-in to receive AI-generated follow-up communications</li>
          <li><strong>Data Processing</strong>: Consent is required before AI processes personal information</li>
          <li><strong>Communication Preferences</strong>: Users can customize or disable AI communications at any time</li>
        </ul>

        <h3>User Rights</h3>
        <ul>
          <li><strong>Opt-Out</strong>: Reply "STOP" to any AI communication to unsubscribe</li>
          <li><strong>Data Access</strong>: Request copies of your data and AI interaction history</li>
          <li><strong>Human Override</strong>: Request human review of any AI-generated decision</li>
          <li><strong>Correction</strong>: Report and correct any AI-generated inaccuracies</li>
        </ul>

        <h2>4. Data Privacy & Security</h2>
        <ul>
          <li>Personal data is not used to train our AI models without explicit consent</li>
          <li>All data processing complies with GDPR, CCPA, and applicable privacy laws</li>
          <li>Secure encryption protects data in transit and at rest</li>
          <li>Social profile enrichment uses only publicly available information</li>
        </ul>

        <h2>5. Accuracy & Limitations</h2>
        <ul>
          <li>AI-generated content may contain inaccuracies or errors</li>
          <li>Lead qualification scores are estimates, not guarantees</li>
          <li>Virtual staging is for visualization purposes only</li>
          <li>Users should independently verify critical information</li>
        </ul>

        <h2>6. Data Deletion Policy</h2>
        <p>
          Users have the right to request deletion of their personal data. To exercise this right, 
          send a deletion request to <a href="mailto:realvibeairealty@gmail.com">realvibeairealty@gmail.com</a>. 
          Deletion will be completed within 30 days and includes all personal data, AI interaction logs, 
          and communication history.
        </p>

        <p>
          For detailed information about data deletion, visit our{' '}
          <a href="/legal/data-deletion" className="text-purple-600 hover:text-purple-700 underline">
            Data Deletion Policy
          </a> page.
        </p>

        <h2>7. Contact & Support</h2>
        <p>For questions about our AI policy or to exercise your rights:</p>
        <ul>
          <li><strong>Email</strong>: <a href="mailto:realvibeairealty@gmail.com">realvibeairealty@gmail.com</a></li>
          <li><strong>Subject Line</strong>: "AI Policy Inquiry" or "Data Rights Request"</li>
          <li><strong>Response Time</strong>: Within 48 hours for general inquiries, 5 business days for data requests</li>
        </ul>

        <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 my-8">
          <h3 className="text-blue-900 mt-0">Our Commitment</h3>
          <p className="text-blue-800 mb-0">
            This policy demonstrates our commitment to responsible AI use in real estate technology. 
            We believe AI should enhance human capabilities while maintaining transparency, user control, and ethical standards.
          </p>
        </div>
      </div>
    </div>
  );
}
