import { NextRequest, NextResponse } from 'next/server';
import { Resend } from 'resend';

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

interface FollowUpData {
  leadId: string;
  name: string;
  email: string;
  priority: 'Hot' | 'Warm' | 'Cold';
  intent?: string;
  daysSinceLastContact: number;
  followUpType: '48h' | '7day' | 'monthly';
  hasResponded: boolean;
}

function generateFollowUpContent(data: FollowUpData): { subject: string; html: string } {
  const businessEmail = process.env.BUSINESS_EMAIL || 'realvibeairealty@gmail.com';
  
  if (data.followUpType === '48h') {
    return {
      subject: `Quick follow-up - ${data.intent === 'demo' ? 'Your demo request' : 'Your inquiry'}`,
      html: `
        <h2>Just checking in!</h2>
        <p>Hi ${data.name},</p>
        
        <p>I wanted to follow up on your recent inquiry about RealVibeAI. I know how busy real estate professionals are, so I'll keep this brief.</p>
        
        ${data.intent === 'demo' ? `
          <p><strong>Your demo request:</strong> We're still preparing your personalized demo. Would you prefer:</p>
          <ul>
            <li>A 15-minute live demo call?</li>
            <li>A self-guided demo link you can explore anytime?</li>
          </ul>
        ` : data.intent === 'pricing' ? `
          <p><strong>Pricing question:</strong> I sent our pricing details yesterday. Do you have any specific questions about:</p>
          <ul>
            <li>Which plan fits your lead volume?</li>
            <li>ROI expectations for your market?</li>
            <li>Integration with your current tools?</li>
          </ul>
        ` : `
          <p><strong>Your question:</strong> I'm here to help with any additional information you need about our AI lead qualification system.</p>
        `}
        
        <p>Simply reply to this email or <a href="https://www.realvibeai.com/realty/contact">schedule a quick 10-minute call</a>.</p>
        
        <p>Best regards,<br>
        RealVibeAI Team<br>
        <a href="mailto:${businessEmail}">${businessEmail}</a></p>
        
        <hr style="margin: 20px 0; border: none; border-top: 1px solid #eee;">
        <p style="font-size: 12px; color: #666;">
          This follow-up was generated by AI. Reply "STOP" to unsubscribe from follow-ups.
        </p>
      `,
    };
  } else if (data.followUpType === '7day') {
    return {
      subject: data.priority === 'Hot' ? 'Still interested in boosting your lead conversion?' : 'One more resource for you',
      html: `
        <h2>${data.priority === 'Hot' ? 'Don\'t let hot leads go cold!' : 'Thought this might help'}</h2>
        <p>Hi ${data.name},</p>
        
        ${data.priority === 'Hot' ? `
          <p>A week ago, you showed strong interest in RealVibeAI. As a fellow real estate professional, I know timing is everything in our business.</p>
          
          <p><strong>Quick question:</strong> What's the biggest challenge you're facing with lead qualification right now?</p>
          <ul>
            <li>Too many unqualified leads wasting your time?</li>
            <li>Missing hot prospects because you can't respond fast enough?</li>
            <li>Spending hours on leads that never convert?</li>
          </ul>
          
          <p>Our AI can solve this in under 10 minutes of setup. <a href="https://www.realvibeai.com/realty/contact">Let's chat briefly</a> about your specific situation.</p>
        ` : `
          <p>I hope you're having a great week! I wanted to share a quick resource that might be valuable for your business.</p>
          
          <p><strong>Free Resource:</strong> <a href="https://www.realvibeai.com/realty/virtual-staging">Virtual Staging Examples</a></p>
          <p>See how AI-powered staging can help your listings stand out and sell faster.</p>
          
          <p>No pressure - just thought this might be useful for your current listings.</p>
        `}
        
        <p>Best regards,<br>
        RealVibeAI Team<br>
        <a href="mailto:${businessEmail}">${businessEmail}</a></p>
        
        <hr style="margin: 20px 0; border: none; border-top: 1px solid #eee;">
        <p style="font-size: 12px; color: #666;">
          This follow-up was generated by AI. Reply "STOP" to unsubscribe from follow-ups.
        </p>
      `,
    };
  } else {
    // Monthly follow-up
    return {
      subject: 'Monthly check-in + new features',
      html: `
        <h2>Quick monthly update</h2>
        <p>Hi ${data.name},</p>
        
        <p>Hope your real estate business is thriving! Just a quick monthly check-in with some updates:</p>
        
        <h3>🆕 What's New:</h3>
        <ul>
          <li><strong>Enhanced AI Scoring:</strong> Our lead qualification is now 23% more accurate</li>
          <li><strong>New Integrations:</strong> Direct sync with popular CRM systems</li>
          <li><strong>Virtual Staging Updates:</strong> Faster processing, better quality</li>
        </ul>
        
        <h3>📊 Industry Insight:</h3>
        <p>Real estate professionals using AI lead qualification are seeing 40% faster response times and 25% higher conversion rates.</p>
        
        <p>Still interested in learning how this could work for your business? <a href="https://www.realvibeai.com/realty/contact">Let's schedule a brief call</a>.</p>
        
        <p>Best regards,<br>
        RealVibeAI Team<br>
        <a href="mailto:${businessEmail}">${businessEmail}</a></p>
        
        <hr style="margin: 20px 0; border: none; border-top: 1px solid #eee;">
        <p style="font-size: 12px; color: #666;">
          This follow-up was generated by AI. Reply "STOP" to unsubscribe from follow-ups.
        </p>
      `,
    };
  }
}

export async function POST(request: NextRequest) {
  try {
    const data: FollowUpData = await request.json();

    // Validate required fields
    if (!data.name || !data.email || !data.priority || !data.followUpType) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Skip follow-up if lead has already responded
    if (data.hasResponded) {
      return NextResponse.json({
        ok: true,
        status: 'skipped',
        reason: 'Lead has already responded',
      });
    }

    // Generate follow-up content
    const { subject, html } = generateFollowUpContent(data);

    // Send follow-up email
    if (resend) {
      try {
        await resend.emails.send({
          from: `RealVibeAI Team <${process.env.BUSINESS_EMAIL || 'realvibeairealty@gmail.com'}>`,
          to: [data.email],
          subject: subject,
          html: html,
        });

        // Log for audit purposes
        console.log('Follow-up sent:', {
          leadId: data.leadId,
          email: data.email,
          priority: data.priority,
          followUpType: data.followUpType,
          daysSinceLastContact: data.daysSinceLastContact,
          timestamp: new Date().toISOString(),
        });

        return NextResponse.json({
          ok: true,
          status: 'sent',
          followUpType: data.followUpType,
          priority: data.priority,
        });
      } catch (error) {
        console.error('Follow-up email failed:', error);
        return NextResponse.json({
          ok: false,
          error: 'Email sending failed',
        }, { status: 500 });
      }
    } else {
      // Log follow-up attempt when email service not configured
      console.log('Follow-up attempted (no email service):', {
        leadId: data.leadId,
        email: data.email,
        priority: data.priority,
        followUpType: data.followUpType,
        subject: subject,
        timestamp: new Date().toISOString(),
      });

      return NextResponse.json({
        ok: true,
        status: 'logged',
        reason: 'Email service not configured',
      });
    }
  } catch (error) {
    console.error('Follow-up API error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
