name: Visual

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  screenshots:
    name: screenshots
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build app
        run: npm run build --no-deps

      - name: Start server
        run: npx next start -p 3000 &
      
      - name: Wait for server
        run: npx wait-on http://localhost:3000

      - name: Run visual tests
        run: npx playwright test --reporter=line

      - name: Upload diff on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: visual-diffs
          path: |
            test-results/**
            playwright-report/**
          if-no-files-found: ignore